spring:
  # 静态资源处理
  resources:
    add-mappings: true
    cache:
      cachecontrol:
        # 缓存响应时间，单位秒
        max-age: 3600
    chain:
      # 资源链自动缓存，默认启动
      cache: true
      # 启用资源链，默认禁用
      enabled: true
      # 启用压缩资源(gzip,brotli)解析，默认禁用
      compressed: true
      # 启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/

  thymeleaf:
    # ????
    cache: false

  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: crystal123
    hikari:
      # ????
      pool-name: DateHikariCP
      # ???????
      minimum-idle: 5
      # ??????????
      idle-timeout: 1800000
      # ?????
      maximum-pool-size: 10
      # ?????????????
      auto-commit: true
      # ?????????
      max-lifetime: 1800000
      # ??????
      connection-timeout: 30000
      # ?????????????
      connection-test-query: SELECT 1

  # redis 配置
  redis:
    # 服务器地址
    host: 127.0.0.1
    # 端口
    port: 6379
    # 数据库
    database: 1
    # 超时时间
    timeout: 10000ms

    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 8
        # 最大连接阻塞时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5

  # RabbitMQ
  rabbitmq:
    # 服务器
    host: 127.0.0.1
    # 用户名
    username: guest
    # 密码
    password: guest
    # 虚拟主机
    virtual-host: /
    # 端口
    port: 5672
    listener:
      simple:
        # 消费者最小数量
        concurrency: 10
        # 消费者最大数量
        max-concurrency: 10
        # 限制消费者每次只处理一条消息，处理完就继续下一条消息
        prefetch: 1
        # 启动时是否默认自动容器，默认true
        auto-startup: true
        # 被拒绝时重新进入队列
        default-requeue-rejected: true
    template:
      retry:
        # 发布重试，默认false
        enabled: true
        # 重试时间，默认1000ms
        initial-interval: 1000ms
        # 默认最大次数，默认3次
        max-attempts: 3
        # 默认最大间隔时间
        max-interval: 10000ms
        # 重试的间隔乘数
        multiplier: 1



# mybatis-plus ??
mybatis-plus:
  # ??Mapper.xml????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ??MyBatis????????
  type-aliases-package: com.seckill.pojo

# Mybatis SQL??????????????Mapper.xml?????
logging:
  level:
    com.seckill.mapper: debug

#